version: '3'

services: 
  mysql:
    container_name: mysql8
    build:
      context: ./.docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${APP_TZ:-Asia/Tokyo}
    ports:
      - ${DOCKER_DB_PORT:-3306}:3306

volumes:
  db-store: